-- Tabla de órdenes para registrar compras de clientes
create table if not exists orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_name text not null,
  client_phone text not null,
  payment_ref text,
  payment_type text, -- 'online' o 'tienda'
  total numeric not null,
  items jsonb not null, -- Aquí guardaremos los platos y cantidades
  note text,
  status text default 'pending' -- Estados: pending, active, completed, canceled
);