-- 1. Create tables if they don't exist

-- Categories
CREATE TABLE IF NOT EXISTS public.categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    "order" INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Clients
CREATE TABLE IF NOT EXISTS public.clients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT,
    phone TEXT UNIQUE NOT NULL,
    rut TEXT,
    total_orders INTEGER DEFAULT 0,
    total_spent NUMERIC DEFAULT 0,
    is_frequent BOOLEAN DEFAULT false,
    first_order_at TIMESTAMPTZ,
    last_order_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Orders
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now(),
    client_id UUID REFERENCES public.clients(id),
    client_name TEXT,
    client_phone TEXT,
    client_rut TEXT,
    items JSONB,
    total NUMERIC,
    status TEXT DEFAULT 'pending',
    payment_type TEXT,
    payment_ref TEXT,
    note TEXT
);

-- Business Info (from BusinessContext)
CREATE TABLE IF NOT EXISTS public.business_info (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT DEFAULT 'Oishi Sushi',
    phone TEXT DEFAULT '+56900000000',
    address TEXT DEFAULT 'Dirección del local',
    instagram TEXT DEFAULT '@oishi.sushi',
    schedule TEXT DEFAULT 'Lunes a Domingo: 12:00 - 23:00',
    bank_name TEXT,
    account_type TEXT,
    account_number TEXT,
    account_rut TEXT,
    account_email TEXT,
    bank_details TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Cash Shifts (for Phase 1 testing)
CREATE TABLE IF NOT EXISTS public.cash_shifts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    opening_balance NUMERIC DEFAULT 0,
    expected_balance NUMERIC DEFAULT 0,
    actual_balance NUMERIC,
    opened_by UUID, -- REFERENCES auth.users(id), but tricky if auth user doesn't exist yet
    opened_by_admin_id UUID,
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    opened_at TIMESTAMPTZ DEFAULT now(),
    closed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Cash Movements
CREATE TABLE IF NOT EXISTS public.cash_movements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shift_id UUID REFERENCES public.cash_shifts(id),
    order_id BIGINT REFERENCES public.orders(id),
    type TEXT CHECK (type IN ('sale', 'income', 'expense')),
    amount NUMERIC,
    description TEXT,
    payment_method TEXT DEFAULT 'cash' CHECK (payment_method IN ('cash', 'card', 'online')),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS Policies (Minimal for testing public access via Anon key if needed)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anon read" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Allow anon insert" ON public.categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update" ON public.categories FOR UPDATE USING (true);

ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anon read" ON public.clients FOR SELECT USING (true);
CREATE POLICY "Allow anon insert" ON public.clients FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update" ON public.clients FOR UPDATE USING (true);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anon read" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Allow anon insert" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update" ON public.orders FOR UPDATE USING (true);

ALTER TABLE public.business_info ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anon read" ON public.business_info FOR SELECT USING (true);
CREATE POLICY "Allow anon insert" ON public.business_info FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update" ON public.business_info FOR UPDATE USING (true);

ALTER TABLE public.cash_shifts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anon read" ON public.cash_shifts FOR SELECT USING (true);
CREATE POLICY "Allow anon insert" ON public.cash_shifts FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update" ON public.cash_shifts FOR UPDATE USING (true);

ALTER TABLE public.cash_movements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anon read" ON public.cash_movements FOR SELECT USING (true);
CREATE POLICY "Allow anon insert" ON public.cash_movements FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update" ON public.cash_movements FOR UPDATE USING (true);

